{%- if values.create_namespace %}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.namespace}}
{%- endif %}
---
kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.name}}
spec:
  instances: ${{values.instances}}
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: ${{values.storage_size}}
  walStorage:
    size: ${{values.storage_size}}
