---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pcf-to-ocp-onboarding
  title: Onboarding template for PCF to OpenShift applications
  description: scaffolder v1beta3 template to onboard an application into OpenShift cluster
  substitute:
    engineering:
      devops: 1
      security: 4
      development_team: 2
  tags:
    - pcf
    - openshift
  links:
    - title: Documentation
      url: https://backstage.io/docs/features/software-templates
      icon: docs
    - title: Source
      url: https://github.com/Vikaspogu/software-templates/blob/main/scaffolder-templates/pcf-to-ocp/template.yaml
      icon: github
spec:
  owner: group:ops
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - manifest_url
      properties:
        manifest_url:
          title: Manifest URL for Repository
          type: string
          description: Unique name of the component
          default: https://github.com/Vikaspogu/pcf-applications/blob/main/basic-spring-boot-api/manifest.yml
  steps:
    - action: fetch:plain:file
      id: fetch-plain-file
      name: Fetch plain file
      input:
        url: ${{parameters.manifest_url}}
        targetPath: manifest.yaml

    - id: transform
      name: transform
      action: roadiehq:utils:jsonata:yaml:transform
      input:
        path: manifest.yaml
        expression: "$.applications[0]"

    - id: log
      name: Console.log
      action: debug:log
      input:
        message: |
          Result: `${{ steps['transform'].output.result }}`

    - id: pcfManifestParser
      name: PCF Manifest parser
      action: custom-utils:pcf-manifest-parser
      input:
        data: ${{ steps['transform'].output.result }}

    - id: fetchBaseApplicationTemplates
      name: Fetch base templates for application repo
      action: fetch:template
      each: ${{parameters.environments}}
      input:
        url: ./skeleton
        values:
          manifestName: ${{steps.pcfManifestParser.output.manifestName}}
          buildPack: ${{steps.pcfManifestParser.output.manifestBuildpack}}
          env: ${{steps.pcfManifestParser.output.manifestEnv}}

    - id: publishToApplication
      name: Create a pull request to application repository
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=vikaspogu&repo=pcf-applications
        branchName: onboarding
        title: Onboarding of new
        update: true
        description: |
          ### Requesting Onboarding of new
