---
apiVersion: crossplane.vpogu.com/v1alpha1
kind: StorageAzure
metadata:
  namespace: ${{values.namespaceName}}
  name: ${{values.appName}}-storage-account
spec:
  compositionRef:
    name: storageazure-composition
  parameters:
    location: ${{values.location}}
    {%- if values.resourceGroupName %}
    resourceGroupName: rg-${{values.resourceGroupName}}
    {%- else %}
    resourceGroupName: rg-${{values.namespaceName}}-${{values.appName}}
    {%- endif %}
    {%- if values.storageAccountName %}
    storageAccountName: account${{values.storageAccountName}}
    {%- else %}
    storageAccountName: account${{values.namespaceName|replace('-', '')}}${{values.appName|replace('-', '')}}
    {%- endif %}
{%- if values.createNamespace %}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.namespaceName}}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
{%- endif %}
