---
apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: Component
{%- endif %}
metadata:
  name: ${{ values.appName }}
  {%- if values.description %}
  description: "${{ values.description }}"
  {%- endif %}
  annotations:
    argocd/app-selector: "${{values.teamName}}-cicd=${{values.appName}}"
    argocd/app-namespace: ${{values.teamName}}-cicd
    janus-idp.io/tekton: ${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=${{values.appName}}'
    sonarqube.org/project-key: ci-pipeline-ref-${{ values.appName }}
  links:
    - url: https://devspaces.apps.dev-acm.v3socp.boo/#https://github.com/${{values.applicationRepoOwner}}/${{values.applicationRepoName}}?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
spec:
  type: ${{ values.applicationType }}
  lifecycle: production
  owner: ${{ values.owner }}
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}
