---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ${{values.teamName}}-application-set
  namespace: ${{values.teamName}}-shared
  labels:
    ${{values.teamName}}-argocd: ${{values.teamName}}-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/idp-team/team-a-gitops
        revision: HEAD
        files:
          - path: "${{values.cluster}}/${{values.teamName}}/*.yaml"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '${{values.teamName}}-{{.path.filename | splitList "-" | first }}'
      labels:
        ${{values.teamName}}-gitops: ${{values.teamName}}-{{.path.filename | splitList "-" | first }}
    spec:
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: ${{values.teamName}}-{{.path.filename | splitList "-" | first }}
      project: ${{values.teamName}}
      sources:
        - chart: hello-world
          helm:
            valueFiles:
              - '$values/{{ .path.path }}/{{.path.filename}}'
          repoURL: 'https://helm.github.io/examples'
          targetRevision: 0.1.0
        - ref: values
          repoURL: 'https://github.com/idp-team/team-a-gitops'
          targetRevision: main
