---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{values.vmName}}-secret
  namespace: ${{ values.namespaceName }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ${{values.vmName}}-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: ${{values.vaultPasswordKey}}