---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: application-onboarding
  title: Application Onboarding template
  description: scaffolder v1beta3 template to onboard an application into OpenShift cluster
  tags:
    - onboarding
    - tekton
    - argocd
  links:
    - title: Documentation
      url: https://backstage.io/docs/features/software-templates
      icon: docs
    - title: Source
      url: https://github.com/Vikaspogu/software-templates/blob/main/scaffolder-templates/application-onboarding/template.yaml
      icon: github
spec:
  owner: group:ops
  type: service
  parameters:
    - title: Onboarding Application
      required:
        - environments
        - cluster
        - teamName
      properties:
        environments:
          type: array
          title: Environments
          description: Select the environments to create
          uniqueItems: true
          ui:widget: checkboxes
          items:
            type: string
            enum:
              - dev
              - test
              - prod
            title: Environment
            ui:
              widget: multiSelect
        cluster:
          title: Select an OpenShift cluster
          type: string
          default: pxm-acm
          enum:
            - pxm-acm
            - dev
            - prod
          enumNames:
            - acm (pxm-acm)
            - development (dev)
            - production (prod)
        teamName:
          title: Name of your team
          type: string
          description: Team name; no spaces are allowed
          pattern: ^[a-z-]*$
          maxLength: 45
          ui:help: 'Hint: Lowercase and only hyphens(-) allowed'
        appName:
          title: Name of your application
          type: string
          description: Application name; no spaces are allowed
          pattern: ^[a-z-]*$
          maxLength: 10
          ui:help: "Hint: Lowercase and only hyphens(-) allowed"
        runTimes:
          title: Application Runtime?
          type: string
          default: java
          enum:
            - java
            - nodejs
            - liberty
          enumNames:
            - Java
            - NodeJS
            - Liberty
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
      dependencies:
        runTimes:
          allOf:
            - if:
                properties:
                  runTimes:
                    const: java
              then:
                properties:
                  runTimeVersion:
                    title: Java Version
                    type: string
                    default: openjdk-11
                    enum:
                      - openjdk-11
                      - openjdk-17
                      - openjdk-21
                    enumNames:
                      - OpenJDK 11
                      - OpenJDK 17
                      - OpenJDK 21
            - if:
                properties:
                  runTimes:
                    const: nodejs
              then:
                properties:
                  runTimeVersion:
                    title: Node Version
                    type: string
                    default: nodejs-11
                    enum:
                      - nodejs-11
                      - nodejs-17
                      - nodejs-21
                    enumNames:
                      - NodeJS 11
                      - NodeJS 17
                      - NodeJS 21

    - title: Provide information about the GitHub location
      required:
        - repository
        - repoName
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
        repository:
          title: Application Repository Organization
          type: string
          default: idp-team
          enum:
            - idp-team
          enumNames:
            - IDP Team Organization (idp-team)
        repoName:
          title: Repository Name
          type: string
          default: application-repo
          enum:
            - application-repo
          enumNames:
            - Sample App Repo (application-repo)
  steps:
    - id: fetchPlatformSkeleton
      name: Fetch base platform template
      action: fetch:template
      each: ${{parameters.environments}}
      input:
        url: ./skeleton/platform
        values:
          cluster: ${{parameters.cluster}}
          fullClusterPath: kustomize/cluster-overlays/${{parameters.cluster}}
          allEnvironments: ${{parameters.environments}}
          environment: ${{each.value}}
          teamName: ${{parameters.teamName}}
          applicationType: resources
    - id: publishToPlatform
      name: Create a pull request to platform repository
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=vikaspogu&repo=openshift-multicluster
        branchName: onboarding/${{parameters.teamName}}
        title: Onboarding of new ${{parameters.teamName}}
        update: true
        description: |
          ### Requesting Onboarding of new ${{parameters.teamName}}

          This pull request is generated by Developer Hub
    - id: labelPrForPlatform
      name: Add labels to PR to platform repository
      action: github:issues:label
      input:
        repoUrl: github.com?owner=vikaspogu&repo=openshift-multicluster
        number: ${{ steps.publishToPlatform.output.pullRequestNumber }}
        labels:
          - onboarding
          - created-by-backstage
    - action: fs:delete
      id: cleanupPlatformTemplates
      name: Cleanup Platform Templates
      input:
        files:
          - kustomize/cluster-overlays/${{parameters.cluster}}

    - id: fetchBaseTenantTemplates
      name: Fetch base templates for tenant repo
      action: fetch:template
      each: ${{parameters.environments}}
      input:
        url: ./skeleton/tenant/
        values:
          cluster: ${{parameters.cluster}}
          allEnvironments: ${{parameters.environments}}
          environment: ${{each.value}}
          teamName: ${{parameters.teamName}}
          applicationType: resources
    - id: publishToTenant
      name: Create a pull request to tenant repository
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=idp-team&repo=team-a-gitops
        branchName: onboarding/${{parameters.teamName}}
        title: Onboarding of new ${{parameters.teamName}}
        update: true
        description: |
          ### Requesting Onboarding of new ${{parameters.teamName}}

          This pull request is generated by Developer Hub
    - id: labelPrForTenant
      name: Add labels to PR to tenant repository
      action: github:issues:label
      input:
        repoUrl: github.com?owner=idp-team&repo=team-a-gitops
        number: ${{ steps.publishToTenant.output.pullRequestNumber }}
        labels:
          - onboarding
          - created-by-developer-hub
    - action: fs:delete
      id: cleanupTenantTemplates
      name: Cleanup tenant Templates
      input:
        files:
          - ${{parameters.cluster}}

    - id: fetchBaseApplicationTemplates
      name: Fetch base templates for application repo
      action: fetch:template
      each: ${{parameters.environments}}
      input:
        url: ./skeleton/application/
        values:
          cluster: ${{parameters.cluster}}
          allEnvironments: ${{parameters.environments}}
          environment: ${{each.value}}
          teamName: ${{parameters.teamName}}
          description: '${{parameters.teamName}}: ${{parameters.appName}}'
          appName: ${{parameters.appName}}
          runTimes: ${{parameters.runTimes}}
          runTimeVersion: ${{parameters.runTimeVersion}}
          applicationType: resources
    - id: publishToApplication
      name: Create a pull request to application repository
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=idp-team&repo=${{parameters.repoName}}
        branchName: onboarding/${{parameters.teamName}}
        title: Onboarding of new ${{parameters.teamName}}
        update: true
        description: |
          ### Requesting Onboarding of new ${{parameters.teamName}}

          This pull request is generated by Developer Hub
    - id: labelPrForApplication
      name: Add labels to PR to application repository
      action: github:issues:label
      input:
        repoUrl: github.com?owner=idp-team&repo=${{parameters.repoName}}
        number: ${{ steps.publishToApplication.output.pullRequestNumber }}
        labels:
          - onboarding
          - created-by-developer-hub
  output:
    links:
      - title: pull request link to platform repo
        url: ${{ steps.publishToPlatform.output.remoteUrl }}
        icon: github
      - title: pull request link to tenant repo
        url: ${{ steps.publishToTenant.output.remoteUrl }}
        icon: github
      - title: pull request link to application repo
        url: ${{ steps.publishToApplication.output.remoteUrl }}
        icon: github
