---
apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.namespace}}
  labels:
    cluster: ${{values.cluster}}
    team: ${{values.teamName}}
    argocd.argoproj.io/managed-by: openshift-gitops
