---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{values.vaultSecretName}}-secret
  namespace: ${{ values.namespaceName }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: ${{values.vaultSecretName}}-secret
  data:
    - secretKey: ${{values.vaultSecretKeyName}}
      remoteRef:
        key: ${{values.vaultSecretName}}
        property: ${{values.vaultSecretKeyName}}
